# Generated by Django 3.0.1 on 2019-12-25 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 12, 25, 19, 55, 46, 231601, tzinfo=utc))),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Catalog')),
            ],
        ),
    ]
